project_id = "gfvhmzhwiwiehucoseld"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[db]
enabled = true
port = 54322
major_version = 15

[functions.weather-api]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.news-aggregator]
verify_jwt = false

[functions.security-monitor]
verify_jwt = true

[functions.analytics-tracker]
verify_jwt = true

[functions.presence-manager]
verify_jwt = true

[functions.backup-generator]
verify_jwt = true