// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfvhmzhwiwiehucoseld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmdmhtemh3aXdpZWh1Y29zZWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjM5ODUsImV4cCI6MjA3MjM5OTk4NX0.QQr_oAZyF4WB-0QZSnZ75RF2_ZLo7X1lJD5XagsCPCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});