// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { supabase as supabaseConfig } from '@/config/environment';
import type { Database } from './types';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  supabaseConfig.url,
  supabaseConfig.anonKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
